---
- name: Connect directly to an ESXi host and collect facts
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: Provide information about a standalone ESXi server
    community.vmware.vmware_about_info:
      validate_certs: false
      hostname: 10.0.0.90   # ESXi hostname
      username: root        # ESXi username
      password: calvin23!   # ESXi password
    register: results

  - name: Display results
    debug:
      var: results

