---
- name: A playbook that runs gather_facts
  hosts: planetexpress
  connection: ssh
  gather_facts: true

  tasks:

  - name: Display all facts
    ansible.builtin.debug:
      var: ansible_facts

